### ISSUE TITLE
`NewConstant` naming causes slowdown when constant matrix gets too large

### ISSUE THREAD

**Issue by chewxy** [gorgonia/gorgonia#177]
`NewConstant` uses the value itself as a name. It uses `fmt.Sprintf("%v", v)` as the name, to be specific. With large matrices(4000000 x 500) was my example, this can cause a significant amount of time spent in there

Perhaps the signature should be changed to this:

```
func NewConstant(v interface{}, name string, opts ...NodeConsOpt) *Node
```

**Comment by barthr** [comment]
Hi,

I think the function doesn't need additional parameters. One of the `NodeConsOpt` is setting the name. We only need to remove the `fmt.Sprintf("%v", v)` in the code and use the `WithName` directly.

Using the code will become:

`NewContant(10, WithName("10"))`

we can default the name field if it's not set or maybe return an error?

**Comment by chewxy** [comment]
+1

**Comment by barthr** [comment]
Should I send a PR for this?

**Comment by chewxy** [comment]
yes please

**Comment by barthr** [comment]
see #180 and let me know if this is what you would like. It is a rather simple change.

**Comment by chewxy** [comment]
please add a check for names to not be `""` somewhere. Appreciate the help.

**Comment by barthr** [comment]
I see! I thought the default value should be `""`. Do you want this check also inside the `WithName` function. That the name won't be assigned when it is empty?

**Comment by chewxy** [comment]
The general rule of constants is that:

* They are unique within a computation
* They are not attached to a graph

Both are technically true of any input nodes as well (i.e. they are free
variables and unbound) but I only enforced it of constants because of the
use of constants
