### ISSUE TITLE
how exactly make examples/charRNN work?

### ISSUE THREAD

**Issue by remotejob** [gorgonia/gorgonia#183]
I tryed simple go run examples/charRNN/main.go

`./../../gorgonia.org/gorgonia/blas.go:6:2: cannot find package "github.com/chewxy/gorgonia/tensor" in any of:
        /exwindoz/home/juno/go/src/github.com/chewxy/gorgonia/tensor (from $GOROOT)
        /exwindoz/home/juno/gowork/src/github.com/chewxy/gorgonia/tensor (from $GOPATH)`

**Comment by chewxy** [comment]
By the looks of it you are using an older version. There was a version
break in v0.8.0, where the package changed.

If you got the package by go get then perhaps try `go get -u
gorgonia.org/gorgonia`

If you got the package by git, perhaps try a git fetch, git update?

LMK if it works

**Comment by remotejob** [comment]
rm -rf  chewxy   from my GOPATH

go get -u -v gorgonia.org/gorgonia

`Fetching https://gorgonia.org/gorgonia?go-get=1
Parsing meta tags from https://gorgonia.org/gorgonia?go-get=1 (status code 200)
get "gorgonia.org/gorgonia": found meta tag get.metaImport{Prefix:"gorgonia.org/gorgonia", VCS:"git", RepoRoot:"https://github.com/gorgonia/gorgonia"} at https://gorgonia.org/gorgonia?go-get=1
package gorgonia.org/gorgonia: gorgonia.org/gorgonia is a custom import path for https://github.com/gorgonia/gorgonia, but /exwindoz/home/juno/gowork/src/gorgonia.org/gorgonia is checked out from https://github.com/chewxy/gorgonia`

**Comment by chewxy** [comment]
Hmm that loooks like some git fuckery. You should clone from
github.com/gorgonia/gorgonia and github.com/gorgonia/tensor

**Comment by remotejob** [comment]
After I delete previous  rm -rf gorgonia.org/

go get -u -v gorgonia.org/gorgonia  download was OK

git clone https://github.com/gorgonia/gorgonia.git

go run main.go 

`# command-line-arguments
./main.go:88:7: undefined: NewLSTMModel
./main.go:88:31: undefined: embeddingSize
./main.go:88:58: undefined: hiddenSizes
./main.go:89:7: undefined: newCharRNN
./main.go:97:22: undefined: run
./main.go:108:8: undefined: newCharRNN
`

**Comment by chewxy** [comment]
go run *.go - the main package is split amongst multiple files

*Xuanyi Chew*
*@chewxy on Twitter*
*Read:* my blog <http://blog.chewxy.com>
*+61403928398*

**Comment by remotejob** [comment]
Ok work hmm.. I never make before go run *.go
