### ISSUE TITLE
improvement  examples/charRNN 

### ISSUE THREAD

**Issue by remotejob** [gorgonia/gorgonia#184]
I try use "examples/charRNN" for more real text but very quickly  prediction stop working 
`Time Taken: 1m9.662684024s      Cost: NaN       Perplexity: NaN`

It will be nice to have some hints to improve result. Maybe change some parameters?

I have file  6.1M size to elaborate.

My  scope arrive to result near:
[https://github.com/karpathy/char-rnn](https://github.com/karpathy/char-rnn)

**Comment by owulveryck** [comment]
Hello,

There are work in progress to enhance and document this example.
I hope I will be able to post a documented version by the end of this month (with a similar goal to reproduce karpathy’s example)

**Comment by chewxy** [comment]
Closing this. The reference LSTM is Olivier Wulveryck's package: https://github.com/owulveryck/lstm
