### ISSUE TITLE
go get unable to get the package

### ISSUE THREAD

**Issue by raokrutarth** [gorgonia/gorgonia#197]
Any ideas on how to fix this? Output of go get below. Help appreciated.

[~ ] $ go get -u gorgonia.org/gorgonia
\# gorgonia.org/gorgonia
scratch/gocode/src/gorgonia.org/gorgonia/walker.go:43:43: cannot use g (type *ExprGraph) as type graph.Directed in argument to topo.SortStabilized:
        *ExprGraph does not implement graph.Directed (wrong type for Edge method)
                have Edge(graph.Node, graph.Node) graph.Edge
                want Edge(int64, int64) graph.Edge
scratch/gocode/src/gorgonia.org/gorgonia/walker.go:53:33: cannot use g (type *ExprGraph) as type graph.Directed in argument to topo.Sort:
        *ExprGraph does not implement graph.Directed (wrong type for Edge method)
                have Edge(graph.Node, graph.Node) graph.Edge
                want Edge(int64, int64) graph.Edge

**Comment by chewxy** [comment]
are you using an older version of gonum

**Comment by chewxy** [comment]
looks like the latest version of gonum/graph broke things... please stand by

**Comment by chewxy** [comment]
@raokrutarth  this issue has been fixed
