### ISSUE TITLE
Slice bug "drop any dimension with size 1"

### ISSUE THREAD

**Issue by matdodgson** [gorgonia/gorgonia#208]
Hi.

Just starting to take a look at the Gorgonia Tensor library for some ML vision stuff. I've found that Slice() is not behaving like Numpy, and my feeling is that this is a bug. Please see the following test code:

```
func TestSlice1(t *testing.T) {
	a := tensor.New(tensor.WithShape(2, 2), tensor.WithBacking([]int{1, 2, 3, 4}))

	err := a.Reshape(1, 1, 2, 2)
	if err != nil {
		panic("bad reshape")
	}

	c, err := a.Slice(gorgonia.S(0), nil, nil, nil)
	if err != nil {
		panic("bad slice")
	}

	if len(c.Shape()) != 3 {
		t.Errorf("bad shape %v", c.Shape())
	}
}
```

After the reshape the Tensor has dimensions 1,1,2,2. After the slice it is 2,2. Since I pass nil as the 2nd parameter to Slice(), my feeling is that it should not remove that dimension, but it does.

If I submit a pull request to fix this, will it be accepted? It's a very simple fix, but could have repercussions if others are using a work around.

**Comment by chewxy** [comment]
You are correct. It is a bug. Bug free is more important than anyone's workflow being preserved. Let's bring this to the right repo, shall we?

**Comment by chewxy** [comment]
github does not have issue moving features - this fix and the PR by @matdodgson can be found here: https://github.com/gorgonia/tensor/issues/30
