### ISSUE TITLE
Gorgonia equivalent of tf/theano scan()

### ISSUE THREAD

**Issue by NMRobert** [gorgonia/gorgonia#219]
Hi,

is there any Gorgonia equivalent of [Theano Scan](http://deeplearning.net/software/theano/library/scan.html) or [Tensorflow Scan](https://www.tensorflow.org/api_docs/python/tf/scan)? There are a number of problems where it's required to accumulate gradients over a loop, and it's not clear how I would approach this in Gorgonia.

Thank you!

**Comment by chewxy** [comment]
Gorgonia was designed to not be turing complete (i.e. no loops or recursion). For the most part you can use multiple `VM`s to achieve that

**Comment by NMRobert** [comment]
Ah, that's very disappointing. I was hoping to use Gorgonia as a general golang autodiff package to back a probabilistic programming tool. Thank you for the (exceptionally!) prompt response though. Cheers.

**Comment by chewxy** [comment]
Oh, you definitely can use Gorgonia as an autodiff tool - just use the `*lispMachine`.

**Comment by chewxy** [comment]
(email me your specific problem and I'll show you how to do it)

**Comment by chewxy** [comment]
Side note @NMRobert : https://github.com/gorgonia/gorgonia/issues/218 (example of how to do autodiff using lispmachine)
