### ISSUE TITLE
Implement maxOp's `.Do()` method

### ISSUE THREAD

**Issue by chewxy** [gorgonia/gorgonia#230]
Turns out the `Max` function is defined, but the actual doing method  is not implemented.

#229  highlights the issue

**Comment by zltgo** [comment]
@chewxy Has the problem been solved?  the max op still can't work in the master version.

**Comment by owulveryck** [comment]
Closing this issue the maxOp implementation seems ok in master thanks to #269.

https://github.com/gorgonia/gorgonia/blob/93e238839b7603ce80c10bb7cff058a77869ea33/op_reduction.go#L111-L120

https://github.com/gorgonia/gorgonia/blob/93e238839b7603ce80c10bb7cff058a77869ea33/op_reduction_test.go#L201-L237

Feel free to reopen if needed.
