### ISSUE TITLE
NewVanillaSolver Step too small

### ISSUE THREAD

**Issue by jerrycraft2** [gorgonia/gorgonia#231]
Hi,
I am testing on the linearregression example code. 
"example_linearregression_test.go"
 
I have change from y=2x+random to y=2x+5000

It takes very long as the steps is very small (0.005) to reach 5000 
solver := NewVanillaSolver(WithLearnRate(0.005), WithClip(5))

Any other solver can speed this up?
Thank you in advance.

**Comment by chewxy** [comment]
In the example it's done on purpose (for tests). You can simply change the learn rate. Also feel free to play with the other solvers. For linear regression, vanilla solvers work best

**Comment by jerrycraft2** [comment]
Hi,
Understood. Thank you very much.

**Comment by chewxy** [comment]
FWIW my next favourite solver is Adagrad (also provided by Gorgonia)
