### ISSUE TITLE
Train model from scratch

### ISSUE THREAD

**Issue by pacpacpacpacpacpac** [gorgonia/gorgonia#243]
Hi,
I m trying to create a deep-learning in golang which is able to recognize emotion from a face picture.

I would like to use gorgonia.
Do think is possible to create and train a model with using your package ?

Thanks

**Comment by chewxy** [comment]
As long as you have the training data, yes

**Comment by pacpacpacpacpacpac** [comment]
ok thanks for your answer i will try !
