### ISSUE TITLE
How to get better prediction

### ISSUE THREAD

**Issue by jerrycraft2** [gorgonia/gorgonia#250]
Hi,
I am running a graph which look like sin wave and have to predict a scalar m.

	m := G.NewScalar(g, Float, G.WithName("m"), G.WithValue(float64(1)))

I get different m result when I start with different figure. Example: start with 0, 1, 2, 3, ...

Can you advice how to get a 1 best prediction of m.

Thank you

**Comment by cfgt** [comment]
Closed due to lack of activity, please re-open the issue if it is still current.
