### ISSUE TITLE
CUDA 10

### ISSUE THREAD

**Issue by chewxy** [gorgonia/gorgonia#253]

**Comment by chewxy** [comment]
As far as we can tell, CUDA 10 seems to work correctly

**Comment by cfgt** [comment]
Test

**Comment by chewxy** [comment]
TODO: get new CUDA capable machine that does not require me to reboot twice everytime I want to use CUDA

**Comment by owulveryck** [comment]
_My other computer it the cloud!_ (terraform and ec2)

Steps: create manually:

* an EBS with a tag "mountPoint:home"
* a security group with a name (I am using "SSHMaison").
* an ssh keyfile (MyKeyName)
* have aws configured on you host for your account (`aws configure` or a key file)

I also have a dns on route 53 (that holds `myzone.com`), but it is not mandatory, you will connect via the IP; you simply need to comment the blocks `data "aws_route53_zone" "myzone" `, and `resource "aws_route53_record" "dev"` in the `tf`files (see below).

Get those [files](https://github.com/owulveryck/dotfiles/tree/master/terraform/devmachine) and create a`terraform.tfvars` that contains:

```
zoneName = "myzone.com"
keyName = "MyKeyName"
```

Run `terraform apply -var 'instance_type=t3.xlarge'`.
Then`mosh ubuntu@dev.myzone.com` and deploy your code in the home (install go, your vimrc, .tmux.conf, `go get etc...`).

If you need a GPU, change the AMI in the file `topology.tf`:
```diff
resource "aws_instance" "dev" {
- ami              = data.aws_ami.ubuntu.id
+ ami              = var.deepLearningAMI
  instance_type     = var.instance_type
  key_name          = var.keyName
  availability_zone = "us-east-1d"
  user_data         = file("postInstall.sh")

  tags = {
    Name = "Dev"
  }
}
```

then `terraform apply -var 'instance_type=g3s.xlarge'` does the magic:
* unmount the EBS
* destroy the host
* create a new host with a GPU and the AMI that have cuda installed
* mount the home

`mosh ubuntu@dev.myzone.com` _et voilà_ you have your files, a GPU and cuda installed!
Once you go to bed: `terraform destroy` so you don't pay anymore...

**Comment by cfgt** [comment]
Test

**Comment by cfgt** [comment]
Test

**Comment by cfgt** [comment]
Closed due to lack of activity, and has also been superseded by other issue reports, such as #297
