### ISSUE TITLE
If and else operation

### ISSUE THREAD

**Issue by jerrycraft2** [gorgonia/gorgonia#255]
Hi,
I need some help. I am unable to get the right cost.
	g := G.NewGraph()
	x := G.NewVector(g, Float, G.WithShape(backinglen), G.WithName("x"), G.WithValue(xT))
	y := G.NewVector(g, Float, G.WithShape(backinglen), G.WithName("y"), G.WithValue(yT))
	m := G.NewScalar(g, Float, G.WithName("m"), G.WithValue(float64(-25)))
	c := G.NewScalar(g, Float, G.WithName("c"), G.WithValue(float64(0)))
	t := G.Must(G.Add(G.Must(G.Mul(m, x)), c))
	prob := G.Must(G.Sub(t, G.Must(G.Floor(t))))    //Will remove integer, left decimal point
	se := G.Must(G.Square(G.Must(G.Sub(prob, y))))
        cost := G.Must(G.Mean(se))

You see, I have use Floor. So, integer is remove. Only left decimal point.
My y also is decimal point.

Let say my prob value is 0.60 and y value is 0.40, then Sub(prob,y) will do just fine. Get 0.20

But let say my prob value is 0.10 and y value is 0.90, then Sub(prob,y) does not seem right to what I need.  I want get 0.20
                       IF Sub(prob,y) < 0.0 THEN Add(Sub(prob,y),1) = Get 0.20

You see, my project is within 360 degree only. Is there a solution to solve this? Is there and IF GREATER THAN ELSE...

Thank you in advance 

Jerry

**Comment by cfgt** [comment]
Closed due to lack of activity, please re-open if this issue is still current.
