### ISSUE TITLE
go get -u gorgonia.org/gorgonia fail

### ISSUE THREAD

**Issue by orange-jacky** [gorgonia/gorgonia#262]
macbookpro:Downloads fredlee$ go version
go version go1.12beta2 darwin/amd64

macbookpro:Downloads fredlee$ go get -u gorgonia.org/gorgonia
go: finding github.com/awalterschulze/gographviz latest
go: finding github.com/leesper/go_rng latest
go: finding gonum.org/v1/gonum/blas latest
go: finding gonum.org/v1/gonum/graph/topo latest
go: finding gonum.org/v1/gonum/graph latest
go: finding gonum.org/v1/gonum/blas/gonum latest
go: finding gonum.org/v1/gonum latest
go: downloading gonum.org/v1/gonum v0.0.0-20190110212618-fe2cf67cb467
go: extracting gonum.org/v1/gonum v0.0.0-20190110212618-fe2cf67cb467
# gorgonia.org/gorgonia
../Documents/develop/go/workspace/pkg/mod/gorgonia.org/gorgonia@v0.8.4/walker.go:43:43: cannot use g (type *ExprGraph) as type graph.Directed in argument to topo.SortStabilized:
	*ExprGraph does not implement graph.Directed (wrong type for From method)
		have From(int64) []graph.Node
		want From(int64) graph.Nodes
../Documents/develop/go/workspace/pkg/mod/gorgonia.org/gorgonia@v0.8.4/walker.go:53:33: cannot use g (type *ExprGraph) as type graph.Directed in argument to topo.Sort:
	*ExprGraph does not implement graph.Directed (wrong type for From method)
		have From(int64) []graph.Node
		want From(int64) graph.Nodes

**Comment by lynic** [comment]
I'm facing the same issue, maybe I have to wait for this package dependencies to be updated.

**Comment by leakyshoe** [comment]
@lynic see https://github.com/gorgonia/gorgonia/pull/241

**Comment by lupo112** [comment]
same problem here

```
# gorgonia.org/gorgonia
..\..\go\pkg\mod\gorgonia.org\gorgonia@v0.9.1\graph.go:569:2: cannot use e (type edge) as type graph.Edge in return argument:
        edge does not implement graph.Edge (missing ReversedEdge method)
..\..\go\pkg\mod\gorgonia.org\gorgonia@v0.9.1\node.go:756:15: cannot use e (type edge) as type graph.Edge in argument to n.g.SetEdge:
        edge does not implement graph.Edge (missing ReversedEdge method)

```

**Comment by chewxy** [comment]
This is an issue with Gonum's versions. Can you try `go mod tidy && go mod vendor` and report back>?

**Comment by lupo112** [comment]
I already tried that. No change.

What works for me was adding to `graph.go` last line:
```
func (e edge) ReversedEdge() graph.Edge { e.from, e.to = e.to, e.from; return e }
```
which is on the master but not on the version v0.9.1. I am using go mod, with this definitions:

```
go 1.12

require (
	gorgonia.org/cu v0.9.0-beta
	gorgonia.org/gorgonia v0.9.1
	gorgonia.org/tensor v0.9.0-beta
)
```

**Comment by decibelcooper** [comment]
Same issue here.  Master branch works fine.

**Comment by cfgt** [comment]
Closed as we are now several versions ahead and this is no longer an issue.
