### ISSUE TITLE
Cannot build with latest version of gonum and Go modules

### ISSUE THREAD

**Issue by leakyshoe** [gorgonia/gorgonia#277]
Steps to reproduce:

```shell
rm -f go.mod && rm -f go.sum && rm -rf vendor
go mod init `basename $(pwd)` && go mod tidy; go mod vendor
go build -mod=vendor -o ./bin/foo ./cmd/service
```

Error received from build:

```go
# gorgonia.org/gorgonia
vendor/gorgonia.org/gorgonia/graph.go:569:2: cannot use e (type edge) as type graph.Edge in return argument:
	edge does not implement graph.Edge (missing ReversedEdge method)
vendor/gorgonia.org/gorgonia/node.go:756:15: cannot use e (type edge) as type graph.Edge in argument to n.g.SetEdge:
	edge does not implement graph.Edge (missing ReversedEdge method)
```

**Comment by chewxy** [comment]
Looking into this. @jokebroker - are you on this?

**Comment by jokebroker** [comment]
Hi @leakyshoe 

Can you try the following steps and let me know whether you still receive the error? (or if you get a 'error loading module requirements', paste it here)

`rm -f go.mod && rm -f go.sum && rm -rf vendor
go mod init `basename $(pwd)` && go get gorgonia.org/gorgonia@master && go mod tidy; go mod vendor
go build -mod=vendor -o ./bin/foo ./cmd/service`

**Comment by leakyshoe** [comment]
go get gorgonia.org/gorgonia@master
go: finding gorgonia.org/gorgonia master
go: gorgonia.org/gorgonia@v0.9.2-0.20190312232230-d8845d55c445: parsing go.mod: unexpected module path "gorgonia"
go: error loading module requirements


Kind Regards

-
Leaky Shoe
leakyshoe@gmail.com

**Comment by leakyshoe** [comment]
FYI :(

```script
rm -f go.mod && rm -f go.sum && rm -rf vendor
go mod init `basename $(pwd)`
go get gorgonia.org/gorgonia@master
->
go: finding gorgonia.org/gorgonia master
go: gorgonia.org/gorgonia@v0.9.2-0.20190312232230-d8845d55c445: parsing go.mod: unexpected module path "gorgonia"
go: error loading module requirements
```

**Comment by hc2683** [comment]
This is still an issue, even with the pushed update. I ended up just making a local copy of v0.9.1, making the changes there directly to properly implement edge, and then using replace in go.mod to reference the local copy.

Another alternative that could work is using go.mod to use an older version of gonum, but they only list version numbers by commits, and I couldn't be bothered finding the exact commit where the ReverseEdge() change was made.

**Comment by jokebroker** [comment]
Looking into this further

**Comment by jokebroker** [comment]
Hey @leakyshoe, @hc2683 

We've done a bunch of testing this side and need to better understand how you're aiming to use modules support in Gorgonia.

The go.mod that exists in the master branch should allow you to build a working version of Gorgonia,  using tensor/v0.9.0-beta & an earlier version of Gonum without ReverseEdge(). We've successfully tested this on a completely fresh (containerised) system.

However, if you clear out the `go.mod` and rerun `go mod init`, the default behaviour is to pull the latest tagged release/latest commit if the repo doesn't use tags. This means you're essentially breaking the chain of dependencies we've specified. 

Why are you expecting this approach to work, and what issue are you attempting to solve by doing this?

Modules support is still new of course, and we want to make the library as easy to use as possible, so please help us understand what you're doing and we can try and get you up and running ASAP.

**Comment by leakyshoe** [comment]
We are not builidng Gorgonia, we are using it in a separate Go application. Create a hello world Go application using Gorgonia and Gonum and setup Go modules for that application, that part in where we get problems which of course is not really your issue but an issue with supporting the new Go modules dependency system

**Comment by hc2683** [comment]
> 
> 
> We are not builidng Gorgonia, we are using it in a separate Go application. Create a hello world Go application using Gorgonia and Gonum and setup Go modules for that application, that part is where we get problems which of course is not really your issue but an issue with supporting the new Go modules dependency system

This is also my use-case. There's no need to rush anything on my behalf, since I got my local dependency hack working without issue. But there may be others who are attempting to do the same who may face this issue (finding that go-getting gorgonia, even the master branch, and then using it in external projects, leads to the errors mentioned in this thread).
