### ISSUE TITLE
Is it possible to port a PyTorch model to this?

### ISSUE THREAD

**Issue by NikEyX** [gorgonia/gorgonia#279]
I have a pytorch model that I would like to deploy to production using Go. Is is possible to do this relatively efficiently with this library? What steps does it involve?

Thanks

**Comment by chewxy** [comment]
Yes, it's possible.  I should probably write a tutorial for that. Can you
email me [username]@gmail.com?

**Comment by blackrez** [comment]
Maybe you can export to onnx and use it with onnx-go. There is a backend based on gorgonia.

https://pytorch.org/tutorials/advanced/super_resolution_with_caffe2.html
https://github.com/owulveryck/onnx-go

**Comment by owulveryck** [comment]
I am closing this issue for now; do not hesitate to reopen it if you think it needs further investigation.
