### ISSUE TITLE
investigate why reshape creates new tensors

### ISSUE THREAD

**Issue by chewxy** [gorgonia/gorgonia#296]
Reported initially by @owulveryck

**Comment by owulveryck** [comment]
I'll give some explanation for the record:

The [`Op`](https://godoc.org/gorgonia.org/gorgonia#Op) interface specifies a `OverwritesInput() int
` method. 

>    // overwriteInput() is a method which states which input the output will be overwriting.
>    // This allows for some efficiency gains as the underlying arrays wouldn't have to be re-allocated.
>   // The method returns an int instead of a bool because potentially different operations may be allowed
>    // to overwrite certain inputs. For example, consider an operation to increment a value:
>   // the IncrementOp would be a unary operator, and assuming we would like to overwrite the input,
>   // the retVal of overwriteInput() will be 0 (inputs[0]).
>    // -1 is returned if overwriting of input is disallowed

The `reshapeOp's overwriteInput()` method returns 0, which means that the input of the operator can be modified:

https://github.com/gorgonia/gorgonia/blob/d84fc3e8c3f7051e07e9bca7e233d7c2caea3ac1/op_tensor.go#L1167 

The [`Do(...)`](https://github.com/gorgonia/gorgonia/blob/d84fc3e8c3f7051e07e9bca7e233d7c2caea3ac1/op_tensor.go#L1139) method of the reshape operator creates new value by cloning its input, which implies that the original data will not be modified:

https://github.com/gorgonia/gorgonia/blob/d84fc3e8c3f7051e07e9bca7e233d7c2caea3ac1/op_tensor.go#L1145

I don't understand if this a mistake or if there is something under the hood that impose this. In this case, we should, at least, document it.

**Comment by owulveryck** [comment]
I made a simple quick-and-dirty patch to test with a `ShallowClone` if the Value is a `*tensor.Dense`

```diff
diff --git a/op_tensor.go b/op_tensor.go
index ec582e9..15b8f0e 100644
--- a/op_tensor.go
+++ b/op_tensor.go
@@ -1142,9 +1142,19 @@ func (op reshapeOp) Do(vals ...Value) (Value, error) {
        }
        var val Value
        var err error
-       if val, err = CloneValue(vals[0]); err != nil {
-               return nil, errors.Wrapf(err, cloneFail, vals[0])
+       switch vals[0].(type) {
+       case tensor.Tensor:
+               if v, ok := vals[0].(*tensor.Dense); ok {
+                       val = v.ShallowClone()
+               } else {
+                       if val, err = CloneValue(vals[0]); err != nil {
+                               return nil, errors.Wrapf(err, cloneFail, vals[0])
+                       }
+               }
+       default:
+               return nil, errors.Errorf(nyiTypeFail, "reshape.Do", "Non tensor")
        }
+
        if !val.Shape().Eq(op.from) {
                return nil, errors.Errorf("Shape mismatch. Input shape is %v. Expected %v", val.Shape(), op.from)
        }
```

The tests are ok, and the bench I run on the tiny yolo v2 model with onnx are a lot better:

```
benchcmp /tmp/tinyyolo-master.bench /tmp/tinyyolo-new-reshape.bench
benchmark          old ns/op     new ns/op     delta
BenchmarkRun-4     960358292     957275056     -0.32%

benchmark          old allocs     new allocs     delta
BenchmarkRun-4     37528          37572          +0.12%

benchmark          old bytes     new bytes     delta
BenchmarkRun-4     343268306     179500499     -47.71%
```

I should test that this has no impact on the gradient computation, but I don't know how to do that.

**Comment by chewxy** [comment]
This issue can  now be closed as @owulveryck had pushed through the changes
