### ISSUE TITLE
go get-u gorgonia assembly failed error

### ISSUE THREAD

**Issue by casijoe5231** [gorgonia/gorgonia#304]
Hey guys, 
whenever I try to use go get gorgonia, I keep hitting the following error:

# gorgonia.org/gorgonia
asm: asmins: illegal 64: 00000 (C:\Users\manikandank\go\src\gorgonia.org\gorgonia\mathutils.s:7)        MOVQ    a+4(FP), SI
asm: asmins: illegal in mode 32: 00000 (C:\Users\manikandank\go\src\gorgonia.org\gorgonia\mathutils.s:7)        MOVQ            a+4(FP), SI (24 18)
asm: asmins: illegal 64: 00005 (C:\Users\manikandank\go\src\gorgonia.org\gorgonia\mathutils.s:8)        MOVQ    b+12(FP), CX
asm: asmins: illegal in mode 32: 00005 (C:\Users\manikandank\go\src\gorgonia.org\gorgonia\mathutils.s:8)        MOVQ            b+12(FP), CX (24 15)
asm: asmins: illegal 64: 00010 (C:\Users\manikandank\go\src\gorgonia.org\gorgonia\mathutils.s:9)        MOVQ    SI, AX
asm: asmins: illegal in mode 32: 00010 (C:\Users\manikandank\go\src\gorgonia.org\gorgonia\mathutils.s:9)        MOVQ            SI, AX (18 14)
asm: asmins: illegal 64: 00013 (C:\Users\manikandank\go\src\gorgonia.org\gorgonia\mathutils.s:10)       CMPQ    CX, $-1
asm: asmins: illegal in mode 32: 00013 (C:\Users\manikandank\go\src\gorgonia.org\gorgonia\mathutils.s:10)       CMPQ            CX, $-1 (15 5)
asm: asmins: illegal 64: 00019 (C:\Users\manikandank\go\src\gorgonia.org\gorgonia\mathutils.s:13)       CQO
asm: asmins: illegal in mode 32: 00019 (C:\Users\manikandank\go\src\gorgonia.org\gorgonia\mathutils.s:13)       CQO (1 1)
asm: asmins: illegal 64: 00021 (C:\Users\manikandank\go\src\gorgonia.org\gorgonia\mathutils.s:14)       IDIVQ   CX
asm: asmins: illegal in mode 32: 00021 (C:\Users\manikandank\go\src\gorgonia.org\gorgonia\mathutils.s:14)       IDIVQ           CX (15 1)
asm: asmins: illegal 64: 00024 (C:\Users\manikandank\go\src\gorgonia.org\gorgonia\mathutils.s:15)       MOVQ    AX, q+20(FP)
asm: asmins: illegal in mode 32: 00024 (C:\Users\manikandank\go\src\gorgonia.org\gorgonia\mathutils.s:15)       MOVQ            AX, q+20(FP) (14 24)
asm: asmins: illegal 64: 00029 (C:\Users\manikandank\go\src\gorgonia.org\gorgonia\mathutils.s:16)       MOVQ    DX, r+28(FP)
asm: asmins: illegal in mode 32: 00029 (C:\Users\manikandank\go\src\gorgonia.org\gorgonia\mathutils.s:16)       MOVQ            DX, r+28(FP) (21 24)
asm: asmins: illegal 64: 00035 (C:\Users\manikandank\go\src\gorgonia.org\gorgonia\mathutils.s:20)       NEGQ    AX
asm: asmins: illegal in mode 32: 00035 (C:\Users\manikandank\go\src\gorgonia.org\gorgonia\mathutils.s:20)       NEGQ            AX (1 14)
asm: asmins: illegal 64: 00038 (C:\Users\manikandank\go\src\gorgonia.org\gorgonia\mathutils.s:21)       MOVQ    AX, q+20(FP)
asm: asmins: illegal in mode 32: 00038 (C:\Users\manikandank\go\src\gorgonia.org\gorgonia\mathutils.s:21)       MOVQ            AX, q+20(FP) (14 24)
asm: asmins: illegal 64: 00043 (C:\Users\manikandank\go\src\gorgonia.org\gorgonia\mathutils.s:22)       MOVQ    $0, r+28(FP)
asm: asmins: illegal in mode 32: 00043 (C:\Users\manikandank\go\src\gorgonia.org\gorgonia\mathutils.s:22)       MOVQ            $0, r+28(FP) (2 24)
asm: assembly failed

**Comment by chewxy** [comment]
What CPU do you use?

**Comment by casijoe5231** [comment]
Intel i5 7400 Quad Core Chip, and also, does CPU really affect this?

**Comment by chewxy** [comment]
can you run `go env`  and paste the output here?

I have a feeling you are running a 32 bit operating system on a 64 bit machine.

**Comment by chewxy** [comment]
(also what OS version are you using)

**Comment by chewxy** [comment]
(also : `go version`)

**Comment by casijoe5231** [comment]
go env output:

set GOARCH=386
set GOBIN=
set GOCACHE=C:\Users\manikandank\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\manikandank\go
set GOPROXY=
set GORACE=
set GOROOT=C:\Users\manikandank\go
set GOTMPDIR=
set GOTOOLDIR=C:\Users\manikandank\go\pkg\tool\windows_386
set GCCGO=gccgo
set GO386=sse2
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m32 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\MANIKA~1\AppData\Local\Temp\go-build273852410=/tmp/go-build -gno-record-gcc-switches

System Info:
![image](https://user-images.githubusercontent.com/30308873/60664943-ca630400-9e80-11e9-86cf-2c70e1f79ea5.png)
****

go version: go1.12.6 windows/386

**Comment by casijoe5231** [comment]
Also, not sure if this affects things, but I dont have admin access on the system mentioned

**Comment by chewxy** [comment]
your `GOARCH` is 386... 

You appear to be using a 32 bit version of Go... but your CPU is a 64 bit CPU and a 64 bit operating system.

**Comment by chewxy** [comment]
I have no idea how we got in this state... the combination isn't really supported in most systems. We  can fix this simply by disallowing 386 in `mathutils.s`

**Comment by casijoe5231** [comment]
@chewxy I figured, thanks for helping out....i will let you know if the 64bit version runs. Cheers

**Comment by chewxy** [comment]
@casijoe5231 does it work?

**Comment by casijoe5231** [comment]
@chewxy Yes it works, after installing the 64-bit version. Cheers!
