### ISSUE TITLE
Fix build at Raspberry Pi

### ISSUE THREAD

**Issue by diegobernardes** [gorgonia/gorgonia#311]
I had some problems to use `gorgonia` with a Raspberry Pi. This are the steps that I did to solve the problem.

1. Update the dependencies to use `github.com/chewxy/math32 1.0.1`.
2. Update the `mathutils` files. The current `asm` implementation is not compatible with the ARM, so I had to skip it with `noasm`, but the problem is that it also skips the pure Go version as well:

```
go build -tags='noasm' main.go
# gorgonia.org/gorgonia
../../../gorgonia/bitmap.go:17:10: undefined: divmod
../../../gorgonia/bitmap.go:35:16: undefined: divmod
../../../gorgonia/bitmap.go:45:16: undefined: divmod
../../../gorgonia/bitmap.go:55:16: undefined: divmod
../../../gorgonia/operations.go:549:20: undefined: divmod
```

And if I add the tag `wasm`, that is used to the pure Go version, other errors happen because it's used internally at the Go runtime to build `wasm`.

**Comment by cpllbstr** [comment]
Faced that error today with Jetson Nano. The solution is pretty simple. There is a error in **mathutils.go** there is function **divmod** that is declared but not implemented. You can simply delete the comment line `// +build wasm` in mathutils_go.go and **divmod** will work fine.

**Comment by bezineb5** [comment]
#321 should have fixed this issue.
