### ISSUE TITLE
Max Panics for dimensions > 2 (and along != everything)

### ISSUE THREAD

**Issue by bdleitner** [gorgonia/gorgonia#326]
I first found this issue when playing with `LogSumExp` (which seems to have other issues, but I'll file something separate if I can confirm there's more of a problem than what the Max issue exposes).

If the dimensions of the input are > 2 and the `along` parameter is neither empty not all dimensions, Max panics.  For repro, see the code below.

The issue appears to be that the `maxOp`'s `Type()` method reduces the number of dimensions by 1 (which already seems wrong as `along` could have more than 1 entry and still not be everything).  On the other hand, `InferShape` simply replaces those axes in the `along` parameter with 1's.

When the resulting node is constructed, there is a `WithShape` option applied (op.go:202) with the shape from `InferShape`, but the node type has already been set and though there is no shape, the tensor number of dimensions is now `n-1`.  Thus, the `WithShape` function panics as `acceptVec` and `acceptScalar` will both be false, but the number of dimensions do not match.

A few potential solutions come to mind (and there may be others I haven't thought of.  I considered seeing about becoming a contributor, and still might, but I still don't know enough about the deep internals to know which approach to take here):

1. Have `Max` (and other reduction ops like `Sum` which also has a similar issue) preserve the number of dimensions.  This would mean not having the `Type()` method reduce the number of dims by 1.
1. Have `InferShape` for the reduction operations remove the axes in the `along` list rather than convert them to 1s.
1. Have `WithShape` be tolerant of mismatched dimensions if the extra dimensions have length 1.

It seems to me that #1 is the best option.  For reduction operations, the values are still there even if they've been reduced along a dimension, and so for any future operations (which may involve broadcasting), it makes sense to keep the number of dimensions the same.

If you agree with that approach, I'm willing to take on making the changes (full disclosure: it would be my first ever contribution to an open source project).

```
package main

import (
	"fmt"

	"gorgonia.org/gorgonia"
	"gorgonia.org/tensor"
)

func main() {
	// This works fine
	doMax(tensor.Shape{5, 7})
	// This panics with:
	// Matrix float64, has 2 dimensions(Shape: ()). Input shape is (1, 7, 11), which has 3 dimensions
	doMax(tensor.Shape{5, 7, 11}) // panics

	// This also panics (if we comment out the above so we can get here)
	// Tensor-3 float64, has 3 dimensions(Shape: ()). Input shape is (1, 7, 11, 13), which has 4 dimensions
	doMax(tensor.Shape{5, 7, 11, 13}) // panics
}

func doMax(shape tensor.Shape) {
	g := gorgonia.NewGraph()
	in := gorgonia.NewTensor(
		g,
		tensor.Float64,
		len(shape),
		gorgonia.WithShape(shape...),
		gorgonia.WithInit(gorgonia.RangedFrom(0)))
	fmt.Println(in.Shape())
	for i := 0; i < len(in.Shape()); i++ {
		out, err := gorgonia.Max(in, i)
		if err != nil {
			fmt.Println(err)
			continue
		}
		fmt.Printf("Max(%d) has shape: %v\n", i, out.Shape())
	}
}
```

**Comment by chewxy** [comment]
I think your approach is fine. I love your approach to these

On the topic of keeping dimensions, in an upcoming PR for supports for Golgi, there is a `KeepDims` function that addresses this. This API is not set. And I would value your input.

Check it out and tell me what you think 

* https://github.com/gorgonia/gorgonia/blob/828e5212d22557556d5828153371aa7a103ee711/shape.go
* https://github.com/gorgonia/gorgonia/blob/828e5212d22557556d5828153371aa7a103ee711/shape_test.go

**Comment by chewxy** [comment]
@bdleitner I have put a release on gorgonia.org/tensor - v0.9.2
