### ISSUE TITLE
Prediction for one set of values after training with batches

### ISSUE THREAD

**Issue by lbellego** [gorgonia/gorgonia#345]
I train with a batch. After training I have to use prediction....how to setup the graph for only one set of input ?

**Comment by lbellego** [comment]
Now I can save weights and bias (thanks again with previous ticket). I have a problem using subgraph. The train use a batch of size n, but the prediction use a size of 1. I didn't find an easy example. I train a time series.

**Comment by owulveryck** [comment]
Can you be a little more specific?
Can you share some code maybe?

Your experience is really interesting, and i’d like to make a tutorial or a set of howto from it on the Gorgonia website.

**Comment by lbellego** [comment]
ok Olivier, hope this is enough.
This is the start of the train function :

```
func train(data []float64, epochs int, verbose bool, neurons ...int) float64 {
	var err error

	xa, ya := createDataset(data, neurons[0])
	inputs := tensor.New(tensor.WithBacking(xa), tensor.WithShape(len(xa)/neurons[0], neurons[0]))
	targets := tensor.New(tensor.WithBacking(ya), tensor.WithShape(len(ya), 1))
	numExamples := len(xa) / neurons[0]
	g := gorgonia.NewGraph()
	x := gorgonia.NewMatrix(g, tensor.Float64, gorgonia.WithShape(numExamples, neurons[0]), gorgonia.WithName("x"))
	y := gorgonia.NewMatrix(g, tensor.Float64, gorgonia.WithShape(numExamples, 1), gorgonia.WithName("y"))

	m := newNN(g, numExamples, neurons)
	if err = m.fwd(x); err != nil {
		log.Fatalf("%+v", err)
	}
```
neurons[] is an array, element 0 is the window size of the time serie, like 5 for me. Next element 1 is the size of the first hidden, etc. Last element is 1.

The size of the input is len(xa)/neurons[0], neurons[0] , for exemple 3127, 5.  There is 3127 elements, 5 for the windows.
When the train is completed I have to use it.
How I put the time series elements is like that : 
 1, 2, 3, 4, 5 ->10  (time series of elements 1 to 5 give 10)
2, 3, 4, 5, 6 -> 22 (next elements 2 to 6 give 22)
etc
When I want to use the training it's with an array of 1,5, not 3127,5
For now I remove the first element 0, add the 3128 elements in the input and call the prediction function. I extract the last result from tabPred, it's the prediction....
```
// prédiction
	vm.Reset()
	xa = append(xa, data[len(data)-1])
	inputs = tensor.New(tensor.WithBacking(xa[1:]), tensor.WithShape((len(xa)-1)/neurons[0], neurons[0]))
	_ = gorgonia.Let(x, inputs)
	if err = vm.RunAll(); err != nil {
		log.Fatalf("Failed at prediction: %v", err)
	}
	tabPred := m.predVal.Data().([]float64)
```

**Comment by lbellego** [comment]
I have saved the weights and bias on each cost<latmincost. I restore them after the training (i did a log to compare the values and the restore is correct). When I give the same set as input for the training the result is different ! m.predVal is not the same ! I don't understand why. Do I have to save/restore another nodes ?

**Comment by owulveryck** [comment]
I did not look closer yet, but I think you may need the `Read` method.
There is a note in this tutorial about this:
https://gorgonia.org/tutorials/iris/#create-the-expression-graph

**Comment by lbellego** [comment]
YES ! thank you ! it's perfect now. And I understand Gorgonia better.
