### ISSUE TITLE
CUDA 10.2 

### ISSUE THREAD

**Issue by nathanhack** [gorgonia/gorgonia#355]
I tried running the examples/convnet using tags='cuda'  I got this error:
```
Failed to execute instruction >= true    [GPU(0)7 GPU(0)6]       GPU(0)8 true    false   true: Happened while attempting to use CUDA to execute >= true   [GPU(0)7 GPU(0)6]       GPU(0)8 true    false   true. Node is e. Register was 8: Unable to perform GteScalar(). The tensor engine does not have the function "elembinop.gte_vs_f64"
````
And tried running examples/convnet_cuda using tags='cuda' and got this error:
```
# gorgonia.org/gorgonia/ops/nn
../../go/pkg/mod/gorgonia.org/gorgonia@v0.9.4/ops/nn/batchnorm_cuda.go:203:41: cannot use alpha (type float64) as type cudnn.Memory in argument to ctx.BatchNormalizationBackward:
        float64 does not implement cudnn.Memory (missing IsNativelyAccessible method)
```
I know from issue #253 CUDA 10 should works.  Any thoughts on what I'm doing wrong?

**Comment by chewxy** [comment]
Oh right - you have to run the command `cudagen` - first you need to `go install gorgonia.org/gorgonia/cmd/cudagen` which generates all the correct "stdlib" for Gorgonia's CUDA integration

**Comment by nathanhack** [comment]
OH wow, your response was super polite. I read the whole readme and remembered the tags bit but totally blanked on the rest... thank you for your patience, I appreciate it! I'll give cudagen a go.

**Comment by chewxy** [comment]
Yea, not ideal. But this is the best way we know of to handle different compute capabillities. A `go:generate` directive might also be useful but we're not sure.

**Comment by nathanhack** [comment]
I'm not sure `go:generate` would be much better. I will say, go.mod for this project worked great until including cuda, then modules kinda broke down. I love modules but the generate phase doesn't work well with them. Too bad nvidia doesn't have a pure go cuda version! 

In other news in case others have the same issue. In addition, to the `LD_LIBRARY_PATH` exports nvidia discussed in post-installation actions, I had to add the following (not mentioned):  `export C_INCLUDE_PATH=${CUDA_HOME}/include:${C_INCLUDE_PATH}` where `CUDA_HOME` was `/usr/local/cuda-<version>` in order to get `gorgonia/cu` to find `cuda.h` on Ubuntu. Apparently, the deb install doesn't set it up.
