### ISSUE TITLE
Error installing gorgonia: go/src/gonum.org/v1/gonum/graph/iterator/nodes.go:135:9: undefined: reflect.MapIter

### ISSUE THREAD

**Issue by cleuton** [gorgonia/gorgonia#356]
I was trying to install gorgonia, following the instructions o the README file, with this: 

$ go get -u gorgonia.org/gorgonia

The result was: 

# gonum.org/v1/gonum/graph/iterator
go/src/gonum.org/v1/gonum/graph/iterator/nodes.go:135:9: undefined: reflect.MapIter

My version of Go: 

$ go version
go version go1.10.4 linux/amd64

**Comment by owulveryck** [comment]
Hello,

The `reflect.MapIter` used by gonum has been introduced in go 1.12 (see [godoc](https://golang.org/pkg/reflect/#MapIter)).
We make an effort to make Gorgonia compatible with go >= latest-1.

Updating your go version should solve your problem.

I am closing this issue; do not hesitate to reopen it if needed.
