### ISSUE TITLE
Addressed 301

### ISSUE THREAD

**Issue by jorgecarleitao** [gorgonia/gorgonia#366]
See https://github.com/gorgonia/gorgonia/issues/301.

Note that this branch currently fails, but I believe that it is due an implementation error in the broadcasting.

Specifically, I was unable to make the following operation:

given a tensor `a` with shape `(2,)` and a tensor `b` with shape `(2,2,2)`, broadcast-add them, such that the result `c` has shape `(2,2,2)`. This stems from the fact that when we try to broadcast `a` into shape `(2,2,2)` (using `left=[]byte{1, 2}`) in the broadcastAdd, it panics.

This situation is demonstrated on the second commit of this MR.

This behavior is not consistent with when we do the same operation where `b` has shape `(2,2)` and `a` is broadcasted using `left=[]byte{1}`, which is valid.

Note that I am assuming that we are following the same rules as the [broadcasting rules of numpy](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)

**Comment by chewxy** [comment]
why closed?

**Comment by jorgecarleitao** [comment]
> why closed?

I have an actual MR, #367, not just an issue. Pressed the wrong button.
