### ISSUE TITLE
Mish property based tests

### ISSUE THREAD

**Issue by chewxy** [gorgonia/gorgonia#370]
Mish is a novel activation function as developed by @digantamisra98 .  The paper may be found here https://arxiv.org/abs/1908.08681

The task is to use property based testing to test the following features as listed in the paper:

* [x] Non-monotonicity
* [x] Non-monotonic derivatives
* [ ] ~~Approximates half of identity at origin (do only `float64` tests)~~ apparently unnecessary - see below

The original issue was raised in #362 and the pull request was in #369 . The original PR didn't include tests owing to my lack of time. Happy to work with anyone willing to tackle this issue

**Comment by ma-hei** [comment]
I'd like to take this on if you're open to questions.

**Comment by chewxy** [comment]
Happy to. Let me know if you need help with anything

**Comment by ma-hei** [comment]
I have two questions.
Question 1:
In general, should the test look as follows?
- to test non-monotonicity, we assert that three values x0, x1, x2 exist, such that x0<x1<x2 and Mish(x0) > Mish(x1) < Mish(x2)
- to test non-monotonic derivatives, we do the same for the derivative of Mish
Question 2:
What is meant by "Approximates half of identity at origin"? I don't understand what "half" means here. Mish is exactly 0 at the origin, isn't it?

Hope my questions are not too naive :)

Thanks!

**Comment by chewxy** [comment]
1. Correct. The derivative may be acquired via a `gorgonia.Grad()`, let me know if you want to know the particulars.
2. This is a question I'd love to know how to test. Two parts to this:
    1. What "approximates identity at origin" means is that the gradient is about the same as the input when the input is at origin (i.e. hovering around 0).  I have no idea how to write property based tests to test this notion.
    2. I do not understand what "half of identity at origin" means, and the paper doesn't really explain it except in some hand wavey way using some "smoothness" figures. Perhaps it'd be prudent for @digantamisra98 to chime in?

**Comment by digantamisra98** [comment]
Basically Identity at origin is a property which can be satisfied by a function f(x) if f(0) = 0 and f'(0) = 1. Approximating nearly half of identity at origin in case of Mish means that f(0) = 0 is true while f'(0) is nearly at 0.6. Though if I'm one to test property based, I'd just test non-montonicity and maybe I'll just test function output values. The identity at origin property can be just confirmed by visualizing the graph.

**Comment by ma-hei** [comment]
I created a PR https://github.com/gorgonia/gorgonia/pull/381. Please feel free to add any comments for improvement.

**Comment by chewxy** [comment]
Closing this now, as all the subissues have been resolved.
