### ISSUE TITLE
Make `cudagen` work with Go Modules

### ISSUE THREAD

**Issue by chewxy** [gorgonia/gorgonia#380]
Currently, the requirement for `cudagen` makes Gorgonia not play nicely with Go Modules when using CUDA. Let's use an example.

## Running Example ##

I write a `package main` in `libfoo/cmd`, consisting of this files:

```
~/go/src/
├── gorgonia.org
│   ├── gorgonia
│   │   └──  ...
│   │   ...
├── libfoo
│   ├── cmd
│   │   └── main.go // imports gorgonia.org/gorgonia
```

## The Current Workflow ##

I have to disable `GO111MODULE` so that `cudagen` can modify the `gorgonia.org/gorgonia` library in `GOPATH` before being able to use it with CUDA. `cudagen` generates a file called `cudamodules.go` in the `gorgonia.org/gorgonia` package

This is not good, because now `gorgonia.org/gorgonia` the package is modified. The directory now looks like this:

```
~/go/src/
├── gorgonia.org
│   ├── gorgonia
│   │   ├──  ...
│   │   └── cudamodules.go // NEW FILE
│   │   ...
├── libfoo
│   ├── cmd
│   │   └── main.go // imports gorgonia.org/gorgonia
```
There are two downside to this:

1. You cannot use Go Modules.
2. Even we can generate `cudamodules.go` outside of a `GOPATH` and put it in the correct location based on the module, it will not match the sum of the library found on Athens or other places. This reduces trust in the library.

Consider that a `*cuda.Engine` has a [`LoadCUDAFunc` method](https://github.com/gorgonia/gorgonia/blob/master/cuda/extension.go#L13) and [`AddToStdLib`](https://github.com/gorgonia/gorgonia/blob/master/cuda.go#L296), I don't see why we can't just generate `cudamodules.go` at the end point (usually a `package main`), that uses these functions. 

## Proposed Workflow ##

In `main.go`, there is a `go:generate cudagen` directive, that when called, generates a `cudamodules.go` file in the directory, leading to this:

```
~/go/src/
├── gorgonia.org
│   ├── gorgonia
│   │   └──  ...
│   │   ...
├── libfoo
│   ├── cmd
│   │   ├── main.go // imports gorgonia.org/gorgonia
│   │   └── cudamodules.go
```
In `cudamodules.go`, instead of 

```
package gorgonia
func init() {
		cudaStdLib = map[string]string { ... }
		cudaStdFuncs = map[string][]string{ ... }
}
```

We have something like this:

```
package $PACKAGENAMEHERE
func init() {
		cudaStdLib := map[string]string { ... } 
		for k, v := range cudaStdLib {
			gorgonia.AddToStdLib(k, v)
		}
}
```

Thus, we do not have to modify the Gorgonia library at compile time. Rather, the standard lib of CUDA functions are handled at the use point.

**Comment by MarkKremer** [comment]
I would like to have a look at this.
