### ISSUE TITLE
Convnet isn't learning?

### ISSUE THREAD

**Issue by strigi-form** [gorgonia/gorgonia#402]
Hello,

I'm new to Gorgonia but not to Go and signal processing.

I'm looking at convnet example:
master branch 5fb5944d4a1f0e599e10850235bcdc936cf05460

It's seems convnet isn't learning as cost isn't decreasing:
2020/05/16 10:29:37 Batches 600
Epoch 0 599 / 600 [====================================================]  99.83%2020/05/16 10:37:13 Epoch 0 | cost 4.399034060185283
Epoch 1 599 / 600 [====================================================]  99.83%2020/05/16 10:44:37 Epoch 1 | cost 4.397099273138944
Epoch 2 599 / 600 [====================================================]  99.83%2020/05/16 10:51:52 Epoch 2 | cost 4.398287264781982
Epoch 3 599 / 600 [====================================================]  99.83%2020/05/16 10:59:18 Epoch 3 | cost 4.398768506057023
Epoch 4 599 / 600 [====================================================]  99.83%2020/05/16 11:06:55 Epoch 4 | cost 4.3982395870493285
Epoch 5 599 / 600 [====================================================]  99.83%2020/05/16 11:13:59 Epoch 5 | cost 4.398134968077715

And when I use the trained NN I got an 11% accuracy... 
Which is a random result.

Regards
Cedric

**Comment by chewxy** [comment]
Looking into this.

**Comment by strigi-form** [comment]
FYI
main.go line 294 solver.Step(gorgonia.NodesToValueGrads(m.learnables())) is silently returning:
No Grad found for w0: No Gradient node/value found for *gorgonia.Node

**Comment by chewxy** [comment]
Ah indeed, I have found the same

```
Epoch 96 599 / 600 [===================================================]  99.83%2020/05/16 23:34:05 Epoch 96 | cost 4.389746779953328
Epoch 97 599 / 600 [===================================================]  99.83%2020/05/16 23:36:36 Epoch 97 | cost 4.389812025584517
Epoch 98 599 / 600 [===================================================]  99.83%2020/05/16 23:39:07 Epoch 98 | cost 4.3900483224035005
Epoch 99 599 / 600 [===================================================]  99.83%2020/05/16 23:41:39 Epoch 99 | cost 4.389761579025348
```

I think @maxsei had discovered the same issue as well.It also occured to me that you're using the `master` branch.

If you look very carefully on the `master` branch, the backpropagation had been commented out:

```
//if _, err = gorgonia.Grad(cost, m.learnables()...); err != nil {
//	log.Fatal(err)
//}
```

This was done pending a fix for an issue @alucantonio discovered. If you checkout to `v0.9.10-performance` it should work. The PR is #391 

If you run it with the #391 branch, it should look something like this:

```
Epoch 0 599 / 600 [====================================================]  99.83%2020/05/18 08:14:43 Epoch 0 | cost 4.385449458130703
Epoch 1 599 / 600 [====================================================]  99.83%2020/05/18 08:19:43 Epoch 1 | cost 4.385448320636018
Epoch 2 599 / 600 [====================================================]  99.83%2020/05/18 08:24:44 Epoch 2 | cost 4.385448132868103
Epoch 3 598 / 600 [====================================================]  99.67%2020/05/18 08:29:44 Epoch 3 | cost 4.385447950163644

```

**Comment by chewxy** [comment]
I will close this issue because it is currently being worked on. You can follow along in #391
