### ISSUE TITLE
Gorgonia v0.9.13 install issues

### ISSUE THREAD

**Issue by jay-jayasimha** [gorgonia/gorgonia#430]
Hello,

I am trying to run a gorgonia app and in the process, am getting the following error. I am running go version 1.13.6 on mac OS Mojave.

../../pkg/mod/gorgonia.org/gorgonia@v0.9.13/blas.go:46:12: cannot use b (type BLAS) as type "gorgonia.org/tensor".BLAS in argument to "gorgonia.org/tensor".Use:
	BLAS does not implement "gorgonia.org/tensor".BLAS (missing Caxpy method)

Can you please provide assistance to fix the issue. Thanks, Jay

**Comment by chewxy** [comment]
Fixed by the latest release @jay-jayasimha v0.9.14
