### ISSUE TITLE
1.15.3 "Import Cycle Not Allowed" on convnet example w/ Cuda 

### ISSUE THREAD

**Issue by phillips96** [gorgonia/gorgonia#445]
Hello, 

I get the following error when trying to run the `convnet cuda` example. 
```
package command-line-arguments
	imports gorgonia.org/gorgonia
	imports gorgonia.org/gorgonia: import cycle not allowed
```
My file structure is as below;
```
├── project
│ ├── convnet.go
│ └── cudamodules.go
```

Note that if I roll back Go to 1.13.9 (Which is fine so by no means urgent), this error does not present itself.

However...
Without piggybacking too much of this issue for another, when I run the following command in the `project` directory, on version 1.13.9, I get the following output which indefinitely hangs. 
```
>>>/usr/local/go-1.13/bin/go run -tags='cuda' .
2020/10/21 10:03:07 Using CUDA build
2020/10/21 10:03:07 gorgonia. true
2020/10/21 10:03:08 p0 (100, 32, 14, 14)
2020/10/21 10:03:08 p2 shape (100, 128, 3, 3)
2020/10/21 10:03:08 r2 shape (100, 1152)
2020/10/21 10:03:08 l2 shape (100, 1152) | (1152, 625)
2020/10/21 10:03:08 l3 name Dropout 0.55(%15) :: Matrix float64 | a3 name ReLU(%14) :: Matrix float64
2020/10/21 10:03:08 DONE
2020/10/21 10:03:08 m.out.Shape (100, 10), y.Shape (100, 10)
2020/10/21 10:03:08 Batches 600
Epoch 0 0 / 600 [------------------------------------------------------]   0.00%
```

Running `nvidia-smi` I can see it has allocated memory to it, but seems to just hang
```
0      6477      C   /tmp/go-build071137485/b001/exe/goHide       470MiB
```

It could be that i'm doing something wrong, but I build the `cudamodules` using the `cudagen` tool. The only strange thing is that I have to remove `//+build cuda` from the top of `convnet.go` prior to running the `cudagen` tool otherwise I get the following 

`2020/10/21 10:07:50 failed to get name of package in working directory. Error: exit status 1. go list error: package .: build constraints exclude all Go files in /path/to/project`. I then add it back in afterwards and it runs, but hangs as mentioned. 

Apologies if the latter is just me being a Go novice!

**Comment by chewxy** [comment]
Yes. CUDA is somewhat broken between CUDA10 and CUDA11, leading to that hang. It's a known issue, hence the `cu` package is being upgraded to CUDA11

**Comment by chewxy** [comment]
The fix to CUDA11 is a few days away.

**Comment by phillips96** [comment]
Fantastic, thank you :smile: 

The issue with  the `import cycle not allowed`, is that a simple fix for later versions, or something i'm doing incorrectly when using the `cudamodules` file on latter versions of Go?

**Comment by chewxy** [comment]
What is the package name on top of `cudamodules.go`

**Comment by phillips96** [comment]
`main`

**Comment by chewxy** [comment]
Wondering if you could send me the code? chewxy [at] gmail.com

**Comment by phillips96** [comment]
Just have done. Subject `Gorgonia #445 & #341`. Thanks

**Comment by chewxy** [comment]
OK I am stumped.

```
$ go version
go version go1.15.3 linux/amd64
$ go run -tags=cuda *.go
2020/10/27 13:59:15 Using CUDA build
2020/10/27 13:59:15 Cuda Activated Gorgonia: true
```

**Comment by phillips96** [comment]
That makes two of us :/ I'll do some more digging but I can just roll back my version of Go for now. 
```
$ go version
go version go1.15.3 linux/amd64
$ go run -tags='cuda' *.go
package command-line-arguments
	imports gorgonia.org/gorgonia
	imports gorgonia.org/gorgonia: import cycle not allowed
$ /usr/local/go-1.13/bin/go run -tags='cuda' *.go
2020/10/27 08:39:47 Using CUDA build
2020/10/27 08:39:47 Cuda Activated Gorgonia: true
```

**Comment by dcu** [comment]
did you tried removing the go mod cache?

**Comment by phillips96** [comment]
I have just removed and updated `Gorgonia` and `CU` packages and now it works fine... Could've been that in combination with cleaning the cache was enough to sort it out so thank you :+1: 

@chewxy, when re-basing on the latest commit, I get the following when running anything with the `cuda` build tag;
```
# gorgonia.org/gorgonia
../../../go/src/gorgonia.org/gorgonia/cuda.go:293:6: calcBlocks redeclared in this block
	previous declaration at ../../../go/src/gorgonia.org/gorgonia/concurrency.go:22:37
```
I see you added `concurrency.go` in your fix for #448. Commenting out the declaration obviously gets around the above. Might be worth a refactor. Happy to close this issue unless you'd prefer to leave it open w.r.t the upcoming CUDA fixes.

**Comment by chewxy** [comment]
embarassingly, that's also fixed in an upcoming commit (found when running test for this)

**Comment by chewxy** [comment]
fixed now in master
