### ISSUE TITLE
CONVNET EXAMPLE CRASHES

### ISSUE THREAD

**Issue by JuanVargas** [gorgonia/gorgonia#446]
I installed Gorgonia on my desktop running Ubuntu 20.02 LTS. The Golang version is 1.15.3. When I ran the code provided in the tutorial I get the following errors:

2020/10/21 10:25:50 Batches 600

Epoch 0 0 / 600    0.00%
Epoch 0 0 / 600    0.00%
Epoch 0 0 / 600    0.00%
Epoch 0 0 / 600    0.00%
Epoch 0 0 / 600    0.00%
Epoch 0 0 / 600    0.00%
Epoch 0 0 / 600    0.00%
Epoch 0 0 / 600    0.00%
Epoch 0 0 / 600    0.00%
Epoch 0 0 / 600    0.00%
Epoch 0 0 / 600    0.00%
Epoch 0 0 / 600    0.00%
Epoch 0 0 / 600    0.00%
Epoch 0 0 / 600    0.00%
Epoch 0 0 / 600    0.00%
Epoch 0 1 / 600    0.17% 11h48m10s
Epoch 0 1 / 600    0.17% 11h48m09s
Epoch 0 1 / 600    0.17% 11h48m06s
Epoch 0 1 / 600    0.17% 11h48m04s
Epoch 0 1 / 600    0.17% 11h47m58s
Epoch 0 1 / 600    0.17% 11h47m54s
Epoch 0 1 / 600    0.17% 11h47m52s
Epoch 0 1 / 600    0.17% 11h47m51s
panic: runtime error: index out of range [2] with length 2

goroutine 130 [running]:
gorgonia.org/gorgonia.(*maxPoolOp).do(0xc000190700, 0x130eb60, 0xc02048a480, 0x130eb60, 0xc020392c60)
	/home/juan/code/go/src/gorgonia.org/gorgonia/op_nn.go:800 +0xbc5
gorgonia.org/gorgonia.(*maxPoolOp).UsePreallocDo(0xc000190700, 0x130a320, 0xc02048a480, 0xc020486100, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
	/home/juan/code/go/src/gorgonia.org/gorgonia/op_nn.go:723 +0x1fe
gorgonia.org/gorgonia.(*execOp).exec(0xc000297720, 0xc01ea1a000, 0x0, 0x0)
	/home/juan/code/go/src/gorgonia.org/gorgonia/vm_tape_nocuda.go:60 +0x1836
gorgonia.org/gorgonia.(*tapeMachine).runall(0xc01ea1a000, 0xc000218000, 0xc0002180c0)
	/home/juan/code/go/src/gorgonia.org/gorgonia/vm_tape.go:235 +0x1ce
created by gorgonia.org/gorgonia.(*tapeMachine).RunAll
	/home/juan/code/go/src/gorgonia.org/gorgonia/vm_tape.go:208 +0x1aa

**Comment by chewxy** [comment]
@JuanVargas  checking it out

**Comment by chewxy** [comment]
I can confirm that it's the latest softmax ops that are causing the issue. Fix coming shortly.

**Comment by chewxy** [comment]
this has been fixed. Sorry for not fixing sooner. I was sick during the weekend.
