### ISSUE TITLE
TapeMachine's behaviour is not idempotent after a call to Reset in some circumstances

### ISSUE THREAD

**Issue by owulveryck** [gorgonia/gorgonia#466]
In this use-case https://github.com/gorgonia/agogo/issues/4 two consecutive execution of the TapeMachine with a call to Reset does not provide the same execution result.

It looks like the `Reset` function should reset the `cpumem` registries like this:

```diff
 // Reset resets the run state of the machine by changing the instruction pointer back to 0
+// and reseting the registry
 func (m *tapeMachine) Reset() {
        m.pc = 0
        m.ExternMetadata.Reset()
@@ -116,6 +117,9 @@ func (m *tapeMachine) Reset() {
                returnValue(m.gpumem[i])
                m.gpumem[i] = nil //
        }
+       for i := range m.cpumem {
+               m.cpumem[i] = nil
+       }
 }
```

I suspect that this instruction https://github.com/gorgonia/gorgonia/blob/12e31c4befd99d1c0844d0d7555b102c3aa11639/vm_tape.go#L509-L512

from the method https://github.com/gorgonia/gorgonia/blob/12e31c4befd99d1c0844d0d7555b102c3aa11639/vm_tape.go#L499 is causing the issue.

A test should validate the hypothesis.

**Comment by chewxy** [comment]
let's merge this

**Comment by dcu** [comment]
ok
