### ISSUE TITLE
Can gorgonia implement Pytorch's Convtranspose2d method?

### ISSUE THREAD

**Issue by GSZS** [gorgonia/gorgonia#493]
Hi,i have a question, Can gorgonia implement Pytorch's Convtranspose2d method?

**Comment by dcu** [comment]
hello, it is not implemented yet but it shouldn't too hard to implement.
Unfortunately we don't have the bandwidth right now to implement it but if you want to implement it I can guide you. Feel free to PM me in the gopher's Slack if that's the case :)

**Comment by GSZS** [comment]
> hello, it is not implemented yet but it shouldn't too hard to implement.
> Unfortunately we don't have the bandwidth right now to implement it but if you want to implement it I can guide you. Feel free to PM me in the gopher's Slack if that's the case :)



> hello, it is not implemented yet but it shouldn't too hard to implement.
> Unfortunately we don't have the bandwidth right now to implement it but if you want to implement it I can guide you. Feel free to PM me in the gopher's Slack if that's the case :)

OK，Thank you
