### ISSUE TITLE
Failing to compile with cuda

### ISSUE THREAD

**Issue by Trey2k** [gorgonia/gorgonia#515]
I have been coming across and issue while trying to use cuda with gorgonia. I have gotten this error now in both windows and arch linux. 
```
../../../../../pkg/mod/gorgonia.org/gorgonia@v0.9.17/cuda.go:141:23: v.Pointer undefined (type Value has no field or method Pointer)
../../../../../pkg/mod/gorgonia.org/gorgonia@v0.9.17/cuda.go:186:48: v.Pointer undefined (type Value has no field or method Pointer)
../../../../../pkg/mod/gorgonia.org/gorgonia@v0.9.17/cuda.go:199:24: retVal.Pointer undefined (type Value has no field or method Pointer)
../../../../../pkg/mod/gorgonia.org/gorgonia@v0.9.17/vm_tape_cuda.go:190:45: dv.d.Pointer undefined (type Value has no field or method Pointer)
../../../../../pkg/mod/gorgonia.org/gorgonia@v0.9.17/vm_tape_cuda.go:197:25: dv.d.Pointer undefined (type Value has no field or method Pointer)
../../../../../pkg/mod/gorgonia.org/gorgonia@v0.9.17/vm_tape_cuda.go:227:50: from.Pointer undefined (type Value has no field or method Pointer)
../../../../../pkg/mod/gorgonia.org/gorgonia@v0.9.17/vm_tape_cuda.go:232:20: to.Pointer undefined (type Value has no field or method Pointer)
```

The cudatest worked without issue. I am not very familiar with gorgonia so if someone is able to point me in the right direction I would appreciate it a lot. Thanks!

**Comment by chewxy** [comment]
You need to generate the kernels for the CUDA program. There's a program called `cudagen` which generates all the operations

**Comment by Trey2k** [comment]
> You need to generate the kernels for the CUDA program. There's a program called `cudagen` which generates all the operations

Thakns for the quick response. I have run cudagen but I am a bit confused what I should do with the generate file. Currently it is in the same directory as my main program. Should this be moved somewhere specific?

**Comment by Trey2k** [comment]
Just some more info, I have now tried with the newest cuda version along with 11.0, 10.1 and 10.0 all result in the same error. It dosnt seem to change the error if cudamodules.go is present or not. The error seems to say there are undefined functions so I am wondering if I need to get a specific version of gorgonia besides 0.9.17. But looking through the versions I dont see any with the interface Value having any method called Pointer.

**Comment by mskyan** [comment]
Anyone (Colab ready) can test this issue:
https://colab.research.google.com/drive/1JMlOwh2kE0mRDZuhcfOCsTQX_YFEmhvU?usp=sharing
